jenkins:
  systemMessage: "Servidor Jenkins preconfigurado para la demostración de la clase."
  numExecutors: 2
  scmCheckoutRetryCount: 2
  mode: NORMAL

unclassified:
  location:
    url: "http://localhost:8080/"

# 1. Credentials Configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "RENDER_DEPLOY_HOOK"
              secret: "${RENDER_DEPLOY_HOOK}"
              description: "Deploy Hook Token/URL para Render"

# 2. Automatic Job Creation using Job DSL
# The following section defines a pipeline job that is automatically created in Jenkins using Job DSL. This job is configured to run the pipeline defined in the `Jenkinsfile` of the GitHub repository.
# Script language: Groovy
jobs:
  - script: |
      pipelineJob('fastapi-ci-cd-pipeline') {
        description('Pipeline principal de CI/CD para la app FastAPI')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/lucasbonanni/devops-python-demo.git')
                }
                branches('main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
